Tony/oracle plugin
metaplex-foundation/developer-hub pull request #102
Opened 2024-05-13 20:24 UTC by tonyboylehub

2024-05-13 20:26 UTC, danenbm requested changes

2024-05-13 20:26 UTC, danenbm commented on src/pages/core/external-plugins/removing-external-plugins.md
> +To to remove the External Plugin Adapter from an Asset you'll need to use the `removeCollectionPlugin()` function.
Typo: Collection

2024-05-13 20:29 UTC, tonyboylehub commented on src/pages/core/external-plugins/removing-external-plugins.md
> +To to remove the External Plugin Adapter from an Asset you'll need to use the `removeCollectionPlugin()` function.
fixed

2024-05-14 20:13 UTC, danenbm approved these changes

2024-05-15 20:37 UTC, merged