Immutability Overview
metaplex-foundation/developer-hub pull request #121
Opened 2024-06-03 15:25 UTC by MarkSackerberg

2024-06-05 14:47 UTC, blockiosaurus commented
This doesn't show up in the Guides tab.

2024-06-05 16:41 UTC, MarkSackerberg commented
You are totally right, thank you for flagging @blockiosaurus 
Fixed it.

2024-06-05 16:50 UTC, blockiosaurus requested changes
Some minor nits but otherwise awesome work!

2024-06-05 16:50 UTC, blockiosaurus commented on src/pages/core/guides/immutability.md
> +In the general context of Digital Assets immutability is often used referring to the metadata of a Token or NFT. In the past this was asked for by communities to make sure that a bought Asset can not
Nit: I think "purchased Asset" is slightly more grammatically correct than "bought Asset"

2024-06-05 16:50 UTC, blockiosaurus commented on src/pages/core/guides/immutability.md
> +- **Immutable Metadata**: The [immutableMetadata](/core/plugins/immutableMetadata) allows to make the Name and URI of a Asset, or a whole collection, unchangeable.
The ImmutableMetadata Plugin

2024-06-05 16:50 UTC, blockiosaurus commented on src/pages/core/guides/immutability.md
> +- **Forbid adding new Plugins**: Core allows to disallow creators to add additional Plugins to an asset using the [addBlocker](/core/plugins/addBlocker) plugin. Without this Plugin the update authori
Core can disallow creators

2024-06-05 16:50 UTC, blockiosaurus commented on src/pages/core/guides/immutability.md
> +- **Plugin Level Immutability**: Some Plugins can have a authority set that is different to the owner or the update authority. When removing this authority this specific plugin can not be changed any
"an authority"
"cannot" from "can not"

2024-06-05 16:50 UTC, blockiosaurus commented on src/pages/core/guides/immutability.md
> +- **Full Immutability**: When removing the update authority of an asset or a collection none of the authority based actions can be triggered anymore. This can for example be changing Metadata or addi
"This includes" instead of "This can for example be"

2024-06-06 09:36 UTC, MarkSackerberg commented
Thank you @blockiosaurus!

2024-06-06 10:04 UTC, blockiosaurus submitted a review, later dismissed

2024-06-11 12:15 UTC, merged