Add assetGate
metaplex-foundation/developer-hub pull request #182
Opened 2024-08-08 12:33 UTC by MarkSackerberg

depends on https://github.com/metaplex-foundation/mpl-core-candy-machine/pull/14

2024-08-08 14:12 UTC, tonyboylehub approved these changes

2024-08-08 14:12 UTC, MarkSackerberg commented
Will merge this when the CM deployment was done. Thank you @tonyboylehub

2024-08-21 10:41 UTC, blockiosaurus requested changes
Asset gate is perfect! Just some comments on Vanity mint

2024-08-21 10:41 UTC, blockiosaurus commented on src/pages/core-candy-machine/guards/vanity-mint.md
> +_The Vanity Mint guard does not require mint settings. It expexts the mint address to match._
Expexts typo

2024-08-21 10:41 UTC, blockiosaurus commented on src/pages/core-candy-machine/guards/vanity-mint.md
> +{% dialect-switcher title="Set up a Candy Machine using the Asset Gate Guard" %}
Copy pasta for asset gate guard

2024-08-21 10:41 UTC, blockiosaurus commented on src/pages/core-candy-machine/guards/vanity-mint.md
> +create(umi, {
Could you add the cases used in the test? 99% of users will probably only care about "starts with", "ends with", and "matches" so we should make copy-pastable examples if it's not too much extra work.

2024-08-21 11:01 UTC, MarkSackerberg commented
@blockiosaurus thanks for the review!

I've added the examples in a list. (and added in addition "starts and ends with")

2024-08-22 16:05 UTC, blockiosaurus approved these changes
Perfect!

2024-08-27 15:00 UTC, merged