add json schema to core
metaplex-foundation/developer-hub pull request #257
Opened 2024-11-12 14:21 UTC by MarkSackerberg

2024-11-19 14:23 UTC, L0STE requested changes

2024-11-19 14:23 UTC, L0STE commented on src/pages/core/json-schema.md
> +The off-chain JSON metadata for Metaplex Core assets is similar to the Metaplex Token Metadata standard. However, since more data can be stored on-chain in the asset itself using plugins, some of the
```suggestion
The off-chain JSON metadata for Metaplex Core assets resembles the Metaplex Token Metadata one. However, with plugins allowing more data to be stored on-chain, fields like creators are now optional but may still be included, as some wallets and tools may render them.
```

2024-11-19 14:23 UTC, L0STE commented on src/pages/core/json-schema.md
> +### Required Fields
Do you think wrapping this section up in a table like in [this section](https://developer-hub-git-core-schma-metaplex-foundation.vercel.app/core/guides/javascript/how-to-create-a-core-nft-asset-with-javascript#uploading-the-metadata) might make it a little more clean? (For both Required and Optional field)

2024-11-19 14:23 UTC, L0STE commented on src/pages/core/json-schema.md
> +Now, we will explore the various fields in the Schema. Examples for different types of Assets such as Videos, Images, 3D Files, and HTML Assets can be found at the bottom of the page. It's important
I think we can put this text where the example are!

2024-11-19 19:02 UTC, tonyboylehub reviewed
Can we possibly add a copyable blank template towards the start maybe? I feel like that might be good to have here.

2024-11-21 10:59 UTC, MarkSackerberg commented
> Can we possibly add a copyable blank template towards the start maybe? I feel like that might be good to have here.

I've changed the order to have the examples at the top.

Also addressed the other nitpicks. Feel free to have a last look @tonyboylehub @L0STE

2024-11-21 13:40 UTC, L0STE approved these changes

2024-11-25 09:13 UTC, merged